server:
  host: WLAN
  port: 8008
  env: dev
  signature: false
  node_name: wlp2s0
api:
  host: WLAN
  port: 8009
  node_name: wlp2s00
database:
  host: 192.168.14.102
  port: 5432
  dbname: mdmp
  user: yunify
  password: zhu88jie
log:
  file:
    path: /pitrix/log/iot/device/
    max_hour: 24
    rotate_hour: 24
  level: DEBUG
redis:
  addr: 127.0.0.1:6379
  db: 0
  password: qingcloud2019
etcd:
  address:
    - http://127.0.0.1:2379
