apiVersion: v1
kind: Service
metadata:
  name: {{ include "rule-manager.name" . }}
  labels:
    app: {{ include "rule-manager.name" . }}
    tkeel.io/prometheus: "true"
spec:
  ports:
    - port: {{ .Values.appPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app: {{ include "rule-manager.name" . }}
